---
- hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Brew install or update preinstalled
    homebrew:
      name: "{{ item }}"
      state: present
    with_items:
      - node
      - git
      - elixir
      - mongodb
      - docker
      - zsh
      - wget

  - name: Brew cask install applications
    homebrew_cask:
      name: "{{ item }}"
      state: present
    with_items:
      - spectacle
      - google-chrome
      - firefox
      - iterm2
      - intellij-idea
      - webstorm
      - atom
      - sublime-text
      - charles
      - spotify
      - slack
      - 1password
      - java

  - name: Install oh my zsh
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

  - name: Copy configured zshrc
    copy:
      src: ./zshrc
      dest: ~/.zshrc

